Config = {}


Config.Debug = false -- will print closest animal outfit held pelt
Config.Bulkitems = { -- Items that you can buy to blackmarket if enabled!
    {
        name = 'bread', -- The name of the item
        price = 2, -- The price to sell this item!
    },
}


Config.Pelts = {
{ animalname = 'a_c_alligator_01', outfit = -281403321, animallabel = 'Spotted Alligator', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_alligator_01', outfit = -561697001, animallabel = 'Alligator', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_alligator_01', outfit = -775023191, animallabel = 'Silver Alligator', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_alligator_01', outfit = false, animallabel = 'Allgiator', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_alligator_02', outfit = false, animallabel = 'Legendary Alligator', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_alligator_03', outfit = 621642275, animallabel = 'Alligator', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_alligator_03', outfit = 929703644, animallabel = 'Alligator', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_alligator_03', outfit = false, animallabel = 'American Alligator', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_armadillo_01', outfit = false, animallabel = 'Armadillo', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_badger_01', outfit = -150174729, animallabel = 'Canadian Badger', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_badger_01', outfit = -1803981367, animallabel = 'American Badger', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_badger_01', outfit = -2046877254, animallabel = 'American Badger', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_badger_01', outfit = 1648068942, animallabel = 'American Badger', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_badger_01', outfit = false, animallabel = 'Badger', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bat_01', outfit = false, animallabel = 'Bat', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_bear_01', outfit = -1091524608, animallabel = 'Black Grizzly', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bear_01', outfit = -1508185179, animallabel = 'Legendary Owiza Grizzly', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bear_01', outfit = -1792054911, animallabel = 'Golden Grizzly', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bear_01', outfit = -2121644801, animallabel = 'DarkBrown Grizzly', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bear_01', outfit = -31550146, animallabel = 'Brown Grizzly', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bear_01', outfit = -551219792, animallabel = 'Northern Grizzly', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bear_01', outfit = 1600962275, animallabel = 'Fighter Grizzly', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bear_01', outfit = 1821962809, animallabel = 'Black Grizzly', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bear_01', outfit = 395667523, animallabel = 'Circus Grizzly', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bear_01', outfit = 597297690, animallabel = 'Fighter Grizzly', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bear_01', outfit = false, animallabel = 'Bear', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bearblack_01', outfit = -134637887, animallabel = 'Black Bear', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bearblack_01', outfit = -2122774804, animallabel = 'Black Bear', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bearblack_01', outfit = 122941845, animallabel = 'Black Bear', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bearblack_01', outfit = false, animallabel = 'Black Bear', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_beaver_01', outfit = -1212478257, animallabel = 'Legendary Beaver', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_beaver_01', outfit = false, animallabel = 'Beaver', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit =  2144062151, animallabel = 'Rocky Mountain Sheep', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = -1151440774, animallabel = 'Rocky Mountain Adult Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = -1372086773, animallabel = 'Desert Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = -156048846, animallabel = 'Desert Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = -163914005, animallabel = 'Sierra Nevada Adult Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = -1667731605, animallabel = 'Desert Sheep', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = -1834180478, animallabel = 'Rocky Mountain Sheep', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = -1899670587, animallabel = 'Desert Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = -2116663991, animallabel = 'Desert Adult Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = -376191772, animallabel = 'Rocky Mountain Sheep', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = -682671307, animallabel = 'Desert Adult Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = -682671307, animallabel = 'Desert Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = -886836096, animallabel = 'Rocky Mountain Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = 1389459977, animallabel = 'Legendary Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = 1572075467, animallabel = 'Sierra Nevada Sheep', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = 689325217, animallabel = 'Sierra Nevada Sheep', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = 696231378, animallabel = 'Seirra Nevada Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = 707006636, animallabel = 'Sierra Nevada Sheep', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = 834383524, animallabel = 'Rocky Mountain Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bighornram_01', outfit = false, animallabel = 'Big Horn Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bluejay_01', outfit = false, animallabel = 'Blue Jay', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_boar_01', outfit = -1874493596, animallabel = 'Boar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_boar_01', outfit = 1509626576, animallabel = 'Boar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_boar_01', outfit = 659982441, animallabel = 'Legendary Boar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_boar_01', outfit = false, animallabel = 'Boar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_boarlegendary_01', outfit = false, animallabel = 'Legendary Boar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buck_01', outfit = -2137753947, animallabel = 'Legendary Buck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buck_01', outfit = 1503798624, animallabel = 'White Buck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buck_01', outfit = 1553811810, animallabel = 'Buck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buck_01', outfit = 1997427892, animallabel = 'Buck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buck_01', outfit = 667304357, animallabel = 'Buck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buck_01', outfit = false, animallabel = 'Buck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buffalo_01', outfit = -1168722760, animallabel = 'Black Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buffalo_01', outfit = -1484190577, animallabel = 'Black Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buffalo_01', outfit = -1514322130, animallabel = 'Black Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buffalo_01', outfit = -1750979848, animallabel = 'Black Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buffalo_01', outfit = -1784505363, animallabel = 'Dark Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buffalo_01', outfit = -1989505391, animallabel = 'Black Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buffalo_01', outfit = -774938341, animallabel = 'Black Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buffalo_01', outfit = -888580579, animallabel = 'Dark Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buffalo_01', outfit = 1257278029, animallabel = 'Black Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buffalo_01', outfit = 1275599965, animallabel = 'Black Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buffalo_01', outfit = 279472558, animallabel = 'Legendary Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buffalo_01', outfit = false, animallabel = 'Buffalo', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_buffalo_tatanka_01', outfit = 47534268, animallabel = 'Legendary Tatanka Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bull_01', outfit = -1236418802, animallabel = 'Hereford Bull', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bull_01', outfit = -1438211309, animallabel = 'Black Angus Bull', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bull_01', outfit = -28012574, animallabel = 'Devon Bull', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_bull_01', outfit = false, animallabel = 'Bull', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_californiacondor_01', outfit = false, animallabel = 'Condor', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_cardinal_01', outfit = false, animallabel = 'Cardinal', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_carolinaparakeet_01', outfit = false, animallabel = 'Carolina Parakeet', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_cedarwaxwing_01', outfit = false, animallabel = 'Cedar Wax Wing', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_chicken_01', outfit = -1460912432, animallabel = 'Leghorn Chicken', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_chicken_01', outfit = -626808707, animallabel = 'Leghorn Chicken', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_chicken_01', outfit = 1165342204, animallabel = 'Java Chicken', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_chicken_01', outfit = false, animallabel = 'Chicken', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_chipmunk_01', outfit = false, animallabel = 'Chipmunk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_cormorant_01', outfit = 13145675, animallabel = 'Cormorant', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_cormorant_01', outfit = 1942190760, animallabel = 'Cormorant', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_cormorant_01', outfit = false, animallabel = 'Cormorant', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_cougar_01', outfit = -287190129, animallabel = 'Northern Cougar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_cougar_01', outfit = -48533502, animallabel = 'Cougar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_cougar_01', outfit = -841151793, animallabel = 'Legendary Giaguaro Cougar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_cougar_01', outfit = 1095382564, animallabel = 'Legendary Tiger Cougar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_cougar_01', outfit = 263759244, animallabel = 'Northern Cougar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_cougar_01', outfit = false, animallabel = 'Cougar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_cow', outfit = false, animallabel = 'Florida Cracker Cow', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_coyote_01', outfit =  1469569555, animallabel = 'Coyote', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_coyote_01', outfit = -101240835, animallabel = 'Coyote', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_coyote_01', outfit = -1394281412, animallabel = 'Coyote', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_coyote_01', outfit = -1680715241, animallabel = 'Coyote', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_coyote_01', outfit = 218671895, animallabel = 'Coyote', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_coyote_01', outfit = 375593826, animallabel = 'Legendary Coyote', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_coyote_01', outfit = false, animallabel = 'Coyote', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_crab_01', outfit = false, animallabel = 'Cuban Crab', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_cranewhooping_01', outfit = -1048557937, animallabel = 'Sandhill Crane', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_cranewhooping_01', outfit = false, animallabel = 'Crane', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_crawfish_01', outfit = false, animallabel = 'Crawfish', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_crow_01', outfit = false, animallabel = 'Crow', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_deer_01', outfit = -1939155122, animallabel = 'Deer', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_deer_01', outfit = -2125383737, animallabel = 'Northern Deer', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_deer_01', outfit = -315064955, animallabel = 'Deer', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_deer_01', outfit = -315064955, animallabel = 'Deer', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_deer_01', outfit = -868965679, animallabel = 'Deer', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_deer_01', outfit = 1875804851, animallabel = 'Deer', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_deer_01', outfit = false, animallabel = 'Deer', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_duck_01', outfit = -1909918104, animallabel = 'Pekin Duck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_duck_01', outfit = 502786908, animallabel = 'Duck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_duck_01', outfit = false, animallabel = 'Duck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_eagle_01', outfit = -539469050, animallabel = 'Golden Eagle', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_eagle_01', outfit = -53949050, animallabel = 'Golden Eagle', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_eagle_01', outfit = 1682396012, animallabel = 'Bald Eagle', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_eagle_01', outfit = 208223462, animallabel = 'Eagle', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_eagle_01', outfit = false, animallabel = 'Ealge', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_egret_01', outfit = -770027479, animallabel = 'Snowy Egret', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_egret_01', outfit = 1437006206, animallabel = 'Little Egert', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_egret_01', outfit = false, animallabel = 'Reddish Egret', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_elk_01', outfit = -307919990, animallabel = 'Rocky Mountain Cow Elk Brown', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_elk_01', outfit = -37747857, animallabel = 'Rocky Mountain Elk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_elk_01', outfit = -566788959, animallabel = 'Legendary White Elk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_elk_01', outfit = -6609035, animallabel = 'Rocky Mountain Cow Elk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_elk_01', outfit = -813373518, animallabel = 'Rocky Mountain Elk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_elk_01', outfit = 1501573693, animallabel = 'Rocky Mountain Elk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_elk_01', outfit = 1762054474, animallabel = 'Rocky Mountain Elk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_elk_01', outfit = false, animallabel = 'Elk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_fox_01', outfit = -1383176768, animallabel = 'American Fox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_fox_01', outfit = -374015026, animallabel = 'Red Fox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_fox_01', outfit = -558577652, animallabel = 'Red Fox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_fox_01', outfit = 413989195, animallabel = 'Grey Fox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_fox_01', outfit = 725155934, animallabel = 'Legendary Fox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_fox_01', outfit = 784342540, animallabel = 'Silver Fox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_fox_01', outfit = false, animallabel = 'Red Fox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_frogbull_01', outfit = -1289532595, animallabel = 'Poisonous Bull Frog', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = true, issmall = false, isbird = false},
{ animalname = 'a_c_frogbull_01', outfit = false, animallabel = 'Bull Frog', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_gilamonster_01', outfit = false, animallabel = 'Gila Monster', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_goat_01', outfit = false, animallabel = 'Goat', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_goosecanada_01', outfit = false, animallabel = 'Canada Goose', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_hawk_01', outfit = -735264359, animallabel = 'Roughlegged Hawk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_hawk_01', outfit = 1402464644, animallabel = 'Red-tailed Hawk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_heron_01', outfit = -1120159737, animallabel = 'Tricolor Heron', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_heron_01', outfit = 1886419143, animallabel = 'Great Blue Heron', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_heron_01', outfit = false, animallabel = 'Great Blue Heron', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_iguana_01', outfit = false, animallabel = 'Green Iguana', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_iguanadesert_01', outfit = false, animallabel = 'Desert Iguana', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_javelina_01', outfit = -1364061621, animallabel = 'Gray Javelina', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_javelina_01', outfit = -520358178, animallabel = 'Collared Javelina', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_javelina_01', outfit = false, animallabel = 'Javelina', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_loon_01', outfit = -560517262, animallabel = 'Loon', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_loon_01', outfit = false, animallabel = 'Common Loon', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_loon_01', outfit = false, animallabel = 'Pacific Loon', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_moose_01', outfit = -1021877830, animallabel = 'Moose', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_moose_01', outfit = -1538725798, animallabel = 'Dark Bull Moose', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_moose_01', outfit = -173971554, animallabel = 'Dark Moose', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_moose_01', outfit = -1861127026, animallabel = 'Dark Bull Moose', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_moose_01', outfit = 1415163930, animallabel = 'Legendary White Moose', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_moose_01', outfit = 2146685523, animallabel = 'Dark Bull Moose', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_moose_01', outfit = false, animallabel = 'Moose', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_muskrat_01', outfit = false, animallabel = 'Muskrat', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_oriole_01', outfit = -2120236310, animallabel = 'Baltimore Oriole', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_oriole_01', outfit = false, animallabel = 'Hooded Oriole', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_owl_01', outfit = -1160541758, animallabel = 'Californian Owl', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_owl_01', outfit = 889331851, animallabel = 'Coastal Owl', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_owl_01', outfit = false, animallabel = 'Great Horned Owl', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_ox_01', outfit = 1567238440, animallabel = 'Ox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_ox_01', outfit = 966583925, animallabel = 'Angus Ox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_ox_01', outfit = false, animallabel = 'Angus Ox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_panther_01', outfit = -1541074772, animallabel = 'Dark Panther', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_panther_01', outfit = -219463491, animallabel = 'Colored Panther', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_panther_01', outfit = 1058681367, animallabel = 'Florida Panther', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_panther_01', outfit = 95938134, animallabel = 'Panther', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_panther_01', outfit = false, animallabel = 'Panther', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_parrot_01', outfit = -1148662080, animallabel = 'Scarlet Parrot', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_parrot_01', outfit = -1566130370, animallabel = 'Great Green Parrot', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_parrot_01', outfit = false, animallabel = 'Parrot', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pelican_01', outfit = -20928664, animallabel = 'White Pelican', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pelican_01', outfit = 1994046600, animallabel = 'Brown Pelican', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pheasant_01', outfit = -1926748177, animallabel = 'Ring-necked pheasant', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pheasant_01', outfit = -535101650, animallabel = 'Chinese Pheasant', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pheasant_01', outfit = 1437006206, animallabel = 'Ringneck Pheasant', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pig_01', outfit =  538936875, animallabel = 'Big China Pig', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pig_01', outfit = -1388818080, animallabel = 'Old Spot Pig', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pig_01', outfit = -773324812, animallabel = 'Pig', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pig_01', outfit = false, animallabel = 'Berkshire Pig', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pigeon', outfit = false, animallabel = 'Pigeon', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_possum_01', outfit = -1655190100, animallabel = 'Opossum', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_possum_01', outfit = 2124910668, animallabel = 'Opossum', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_possum_01', outfit = false, animallabel = 'Opposum', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_prairiechicken_01', outfit = false, animallabel = 'Prairie Chicken', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_pronghorn_01', outfit = -1057615530, animallabel = 'Sonoran Pronghorn(M)', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = -1085058996, animallabel = 'Pronghorn (F)', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = -1235944432, animallabel = 'Sonoran Pronghorn(M)', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = -2108783749, animallabel = 'Baja Pronghorn(F)', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = -386220147, animallabel = 'Desert Sheep', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = -87794079, animallabel = 'Sonoran Pronghorn(F)', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = -967163299, animallabel = 'Baja Pronghorn(M)', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = 1011154058, animallabel = 'Baja Pronghorn(M)', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = 1126570175, animallabel = 'Sonoran Pronghorn(M)', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = 1900330120, animallabel = 'Baja Pronghorn(F)', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = 1950818712, animallabel = 'Desert Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = 1999086413, animallabel = 'Desert Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = 2042092622, animallabel = 'Sonoran Pronghorn(F)', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = 2098180041, animallabel = 'Baja Pronghorn(M)', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = 2109101419, animallabel = 'Baja Pronghorn(F)', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = 389666332, animallabel = 'Sonoran Pronghorn(F)', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = 43290926, animallabel = 'Rocky Mountain Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = 697666614, animallabel = 'Desert Adult Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_pronghorn_01', outfit = false, animallabel = 'Pronghorn Doe', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_quail_01', outfit = false, animallabel = 'Quail', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_rabbit_01', outfit = -1153495004, animallabel = 'Northern Rabbit', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_rabbit_01', outfit = -1299761151, animallabel = 'Rabbit', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_rabbit_01', outfit = -713808113, animallabel = 'Rabbit', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_rabbit_01', outfit = 1383633612, animallabel = 'Rabbit', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_rabbit_01', outfit = 1621798704, animallabel = 'Rabbit', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_rabbit_01', outfit = false, animallabel = 'Rabbit', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_raccoon_01', outfit =  -969479795, animallabel = 'Brown Raccoon', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_raccoon_01', outfit = 1164706043, animallabel = 'Grey Raccoon', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_raccoon_01', outfit = 1257983596, animallabel = 'Raccoon', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_raccoon_01', outfit = 158140748, animallabel = 'Raccoon', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_raccoon_01', outfit = 1939496279, animallabel = 'Black Raccoon', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_raccoon_01', outfit = 2099062422, animallabel = 'Raccoon', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_raccoon_01', outfit = false, animallabel = 'Raccoon', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_rat_01', outfit = -1107406441, animallabel = 'Rat', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_rat_01', outfit = -1851596605, animallabel = 'Rat', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_rat_01', outfit = -523178350, animallabel = 'Rat', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_rat_01', outfit = -809569000, animallabel = 'Rat', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_rat_01', outfit = false, animallabel = 'Rat', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_raven_01', outfit = false, animallabel = 'Raven', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_redfootedbooby_01', outfit = false, animallabel = 'Red Footed Booby', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_robin_01', outfit = false, animallabel = 'Robin', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_rooster_01', outfit = 1234539032, animallabel = 'Java Rooster', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_rooster_01', outfit = 1703895940, animallabel = 'Italian Rooster', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_rooster_01', outfit = false, animallabel = 'Rooster', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_roseatespoonbill_01', outfit = false, animallabel = 'Roseata Spoonbill', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_seagull_01', outfit = -1313615167, animallabel = 'Ring-billed Seagull', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_seagull_01', outfit = -595873616, animallabel = 'Laughing Seagull', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_seagull_01', outfit = false, animallabel = 'Seagull', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = true},
{ animalname = 'a_c_sheep_01', outfit = -2035169657, animallabel = 'Sheep', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_sheep_01', outfit = -2036030698, animallabel = 'Black Sheep', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_sheep_01', outfit = -314862125, animallabel = 'Black Sheep', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_sheep_01', outfit = -416122861, animallabel = 'Sheep', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_sheep_01', outfit = 1887700917, animallabel = 'Sheep', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_sheep_01', outfit = false, animallabel = 'Sheep', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_skunk_01', outfit = -1471195588, animallabel = 'Skunk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_skunk_01', outfit = -256370740, animallabel = 'Skunk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_skunk_01', outfit = 1451635371, animallabel = 'Skunk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_skunk_01', outfit = false, animallabel = 'Skunk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snake_01', outfit = 1247593036, animallabel = 'Diamondback Rattlesnake', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snake_01', outfit = 1844089285, animallabel = 'Forest Rattlesnake', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snake_01', outfit = 644441945, animallabel = 'Legendary Rattlesnake', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snake_01', outfit = false, animallabel = 'Black-Tailed Rattlesnake', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snakeblacktailrattle_01', outfit = false, animallabel = 'Black tailed rattle snake', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snakeferdelance_01', outfit = -2078090703, animallabel = 'Sunglow Boa', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snakeferdelance_01', outfit = -60896296, animallabel = 'Rainbow Boa', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snakeferdelance_01', outfit = false, animallabel = 'Fer-de-Lance', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snakeredboa_01', outfit = -1120159737, animallabel = 'Tricolor Heron', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snakeredboa_01', outfit = false, animallabel = 'Boa', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snakeredboa_01', outfit = false, animallabel = 'Pacific Loon', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snakeredboa10ft_01', outfit = false, animallabel = 'Legendary Boa', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snakewater_01', outfit = -1122285933, animallabel = 'Water Snake', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snakewater_01', outfit = 463389154, animallabel = 'Water Snake', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_snakewater_01', outfit = false, animallabel = 'Water Snake', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_songbird_01', outfit = -220316070, animallabel = 'Scarlet songbird', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_songbird_01', outfit = false, animallabel = 'a_c_songbird_01', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_sparrow_01', outfit = -1540150672, animallabel = 'Golden Sparrow', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_sparrow_01', outfit = -737163478, animallabel = 'Common Sparrow', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_sparrow_01', outfit = 1537484073, animallabel = 'Sparrow', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_sparrow_01', outfit = false, animallabel = 'Sparrow', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_squirrel_01', outfit = -1313615167, animallabel = 'Grey Squirrel', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_squirrel_01', outfit = -953201595, animallabel = 'Red Squirrel', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_squirrel_01', outfit = 2063794405, animallabel = 'Black Squirrel', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_squirrel_01', outfit = 395908581, animallabel = 'Red Squirrel', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_squirrel_01', outfit = 786903081, animallabel = 'Grey Squirrel', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_squirrel_01', outfit = false, animallabel = 'Grey Squirrel', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_toad_01', outfit =  675288905, animallabel = 'Poisoning Toad', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_toad_01', outfit = 1703895940, animallabel = 'Desert Toad', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_toad_01', outfit = false, animallabel = 'Toad', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_turkey_01', outfit = false, animallabel = 'Turkey', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_turkey_02', outfit = false, animallabel = 'Turkey', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_turkeywild_01', outfit = -1205411791, animallabel = 'Rio Grande Turkey', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_turkeywild_01', outfit = -1360292266, animallabel = 'Rio Grande Turkey', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_turkeywild_01', outfit = 1577016527, animallabel = 'Rio Grande Turkey', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_turkeywild_01', outfit = false, animallabel = 'Wild Turkey', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_turtlesnapping_01', outfit = false, animallabel = 'Snapping Turtle', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_vulture_01', outfit = -2141465661, animallabel = 'Western Vulture', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_vulture_01', outfit = -872382606, animallabel = 'Eastern Vulture', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_vulture_01', outfit = false, animallabel = 'Western Vulture', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_wolf_medium', outfit =  1497369321, animallabel = 'Timber Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_wolf_medium', outfit = -108158466, animallabel = 'Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_wolf_medium', outfit = -1204380190, animallabel = 'Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_wolf_medium', outfit = -352089994, animallabel = 'Gray Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_wolf_medium', outfit = 1596049292, animallabel = 'Gray Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_wolf_medium', outfit = 1827496739, animallabel = 'Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_wolf_medium', outfit = 184083808, animallabel = 'Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_wolf_medium', outfit = 618007766, animallabel = 'Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_wolf_medium', outfit = false, animallabel = 'Medium Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_wolf_small', outfit = -1204380190, animallabel = 'Small Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_wolf_small', outfit = -290259928, animallabel = 'Small Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_wolf_small', outfit = -588162907, animallabel = 'Small Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_wolf_small', outfit = 618007766, animallabel = 'Small Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_wolf_small', outfit = false, animallabel = 'Small Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'A_C_Wolf', outfit = -1039768986, animallabel = 'Big Grey Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'A_C_Wolf', outfit = -1204380190, animallabel = 'Big wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'A_C_Wolf', outfit = -1837792443, animallabel = 'Timber Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'A_C_Wolf', outfit = -1990288526, animallabel = 'Big Gray Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'A_C_Wolf', outfit = -352089994, animallabel = 'Big Grey Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'A_C_Wolf', outfit = 1904899014, animallabel = 'Big Gray Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'A_C_Wolf', outfit = 618007766, animallabel = 'Big wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'A_C_Wolf', outfit = 922027494, animallabel = 'Legendary Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'A_C_Wolf', outfit = false, animallabel = 'Big Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'a_c_woodpecker_01', outfit = false, animallabel = 'Red-bellied Woodpecker', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'a_c_woodpecker_02', outfit = false, animallabel = 'Pileated Woodpecker', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'mp_a_c_alligator_01', outfit = -1203226280, animallabel = 'Legendary Banded Alligator', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_alligator_01', outfit = -834316719, animallabel = 'Legendary Alligator', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_alligator_01', outfit = -972401444, animallabel = 'Legendary Sun Alligator', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_alligator_01', outfit = 1659735712, animallabel = 'Legendary Teca Alligator', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'mp_a_c_bear_01', outfit = -1210544352, animallabel = 'Legendary Ridgeback Spirit Bear', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_bear_01', outfit = -1508185179, animallabel = 'Legendary Owiza Bear', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_bear_01', outfit = 147271932, animallabel = 'Legendary Golden Spirit Bear', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_bear_01', outfit = 892552081, animallabel = 'Legendary Deadly Bear', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_beaver_01', outfit = 1321671943, animallabel = 'Legendary Grey Beaver', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_beaver_01', outfit = 334014283, animallabel = 'Legendary White Beaver', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_beaver_01', outfit = 766106317, animallabel = 'Legendary Black Beaver', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_bighornram_01', outfit = -1369857002, animallabel = 'Legendary Chalk Horn Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'mp_a_c_bighornram_01', outfit = -1513285038, animallabel = 'Legendary GreatHorn Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_bighornram_01', outfit = -1667956595, animallabel = 'Legendary Rutile Horn Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_bighornram_01', outfit = -1742831887, animallabel = 'Legendary Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_bighornram_01', outfit = 797910655, animallabel = 'Legendary Gabbro Horn Ram', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_boar_01', outfit =  -661738271, animallabel = 'Legendary Cogi Boar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_boar_01', outfit = -188652218, animallabel = 'Legendary Icahi Boar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_boar_01', outfit = -978876653, animallabel = 'Legendary Wakpa Boar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_boar_01', outfit = 779310599, animallabel = 'Legendary Wildhog', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_boar_01', outfit = 892552081, animallabel = 'Legendary Wildhog', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_buck_01', outfit = -1141848787, animallabel = 'Legendary Shadow Buck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_buck_01', outfit = -1381586791, animallabel = 'Legendary Snow Buck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_buck_01', outfit = -1483933996, animallabel = 'Legendary Buck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_buck_01', outfit = -1617752974, animallabel = 'Legendary Mudrunner Buck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_buck_01', outfit = 1388122081, animallabel = 'Legendary Buck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_buck_01', outfit = 610434548, animallabel = 'Legendary Buck', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_buffalo_01', outfit = -139301483, animallabel = 'Legendary Tatanka Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_buffalo_01', outfit = -378711797, animallabel = 'Legendary Winyan Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_buffalo_01', outfit = -605047280, animallabel = 'Legendary Payata Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_buffalo_01', outfit = 610434548, animallabel = 'Legendary Bison', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_cougar_01', outfit = -435549190, animallabel = 'Legendary Black Cougar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_cougar_01', outfit = -835665806, animallabel = 'Legendary Maza Cougar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_cougar_01', outfit = 2096045552, animallabel = 'Legendary Iguga Cougar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'mp_a_c_cougar_01', outfit = 693761739, animallabel = 'Legendary Sapa Cougar', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_coyote_01', outfit = 1155641591, animallabel = 'Legendary Milk Coyote', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_coyote_01', outfit = 1662119255, animallabel = 'Legendary Midnight Paw Coyote', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_coyote_01', outfit = 459539009, animallabel = 'Legendary Coyote', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_coyote_01', outfit = 807110531, animallabel = 'Legendary Red Streak Coyote', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_elk_01', outfit = -44203702, animallabel = 'Legendary Katata Elk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'mp_a_c_elk_01', outfit = 1810685543, animallabel = 'Legendary Inahme Elk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_elk_01', outfit = 319532198, animallabel = 'Legendary Ozuya Elk', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_fox_01', outfit = -1558958207, animallabel = 'Legendary Ota Fox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false, isbird = false},
{ animalname = 'mp_a_c_fox_01', outfit = -1936391549, animallabel = 'Legendary Marble Fox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false, isbird = false},
{ animalname = 'mp_a_c_fox_01', outfit = -1936391549, animallabel = 'Legendary Marble Fox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false, isbird = false},
{ animalname = 'mp_a_c_fox_01', outfit = 131922197, animallabel = 'Legendary Cross Fox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_fox_01', outfit = 1692953176, animallabel = 'Legendary Fox', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_moose_01', outfit = 206311939, animallabel = 'Legendary Knight Moose', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_moose_01', outfit = 538065295, animallabel = 'Legendary Snowflake Moose', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_moose_01', outfit = 878961202, animallabel = 'Legendary Ruddy Moose', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_panther_01', outfit = -360941481, animallabel = 'Legendary Iwakta Panther', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = true, isbird = false},
{ animalname = 'mp_a_c_panther_01', outfit = -606676212, animallabel = 'Legendary Ghost Panther', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_panther_01', outfit = 925551623, animallabel = 'Legendary Panther', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_panther_01', outfit = 968333004, animallabel = 'Legendary Nightwalker Panther', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_wolf_01', outfit = -1428269438, animallabel = 'Legendary Moonstone Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_wolf_01', outfit = -1513285038, animallabel = 'Crow', price = 12, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_wolf_01', outfit = -1657259210, animallabel = 'Legendary Onyx Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_wolf_01', outfit = 1654093036, animallabel = 'Legendary Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},
{ animalname = 'mp_a_c_wolf_01', outfit = 263659570, animallabel = 'Legendary Emerald Wolf', price = 10, rewarditem1 = false, rewarditem2 = false, rewarditem3 = false, issmall = false, isbird = false},



}